title: AirNotifier
description: Easy to use push notifications for iOS, Android and Windows
google_analytics: UA-52392227-1
show_downloads: false
theme: jekyll-theme-hacker

gems:
  - jekyll-mentions
